# Generated by Django 5.2.5 on 2025-08-16 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votacao", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opcao",
            name="votos",
        ),
        migrations.CreateModel(
            name="Voto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_voto",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data do voto"
                    ),
                ),
                (
                    "opcao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="votacao.opcao"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto",
                "verbose_name_plural": "Votos",
                "unique_together": {("usuario", "opcao")},
            },
        ),
    ]
